FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY . /app

# Add these for psycopg2 build
RUN apt-get update && apt-get install -y \
    libpq-dev gcc

RUN pip install -r requirements_job.txt

ENV PYTHONPATH=/app
CMD ["python", "job/main.py"]