# Dockerfile
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /kc_app

# Add these for psycopg2 build
RUN apt-get update && apt-get install -y \
    libpq-dev gcc

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD celery -A oaklab worker --loglevel=info